### ISSUE TITLE
Log access for CS

### ISSUE THREAD

**Issue by Neex101** [YetiTool/console-raspi3b-plus-platform#4]
Simulation of how CS would help a customer in the field. Walk through a scenario.

**Comment by Neex101** [comment]
USB
WiFi
Email?

**Comment by Klazomenai** [comment]
Updated the [console-raspi3b-plus-platform Wiki](https://github.com/YetiTool/console-raspi3b-plus-platform/wiki) with some initial details how to pull out the relevant logs when on physically logged on the Pi.

**Comment by Klazomenai** [comment]
Update in terms of recently discussed solutions. It looks like e-mail (SB out in the wild >> Support) won't be an option for the short term as we have to deal with mail relays and overly complex infrastructure. Given we already have remote access planned (for remote support options) it makes most sense for the log access to (temporarily open the same SSH support reverse tunnel to the support host and) dump logs down the same tunnel direct to the support host.

How we get the logs off of the support host is out of scope for this ticket and will be discussed in other tickets.
