### ISSUE TITLE
avrdude config update

### ISSUE THREAD

**Issue by Klazomenai** [YetiTool/console-raspi3b-plus-platform#41]
## Acceptance criteria
`/etc/avrdude.conf` to include the line: `reset=17;` within the following definition:
```
programmer
  id    = "wiring";
  desc  = "Wiring";
  type  = "wiring";
  connection_type = serial;
;
```

**Comment by LettyYeti** [comment]
`reset = 17;`  >> wiring programmer 

`dtoverlay=pi3-miniuart-bt` >> /boot/config.txt

**Comment by Klazomenai** [comment]
Edited. Thanks @LettyYeti

**Comment by Klazomenai** [comment]
Resolved by https://github.com/YetiTool/console-raspi3b-plus-platform/pull/47
