### ISSUE TITLE
FTP server to open Job Cache directory

### ISSUE THREAD

**Issue by Neex101** [YetiTool/console-raspi3b-plus-platform#5]
As a user of the Smart Bench,
I want to access EasyCut over the Wifi,
So that I can save my G-Code using Fusion.

**Comment by Klazomenai** [comment]
- Example of [FTP build steps](https://www.raspberrypi.org/documentation/remote-access/ftp.md) for the Pi
- Will need to hard code directory inside the current checked out repo of EasyCut: `/home/pi/easycut-smartbench/src/jobCache`
- Will use the same `pi` user as initial pass

**Comment by Klazomenai** [comment]
Having to drop the `S` from `SFTP` as Fusion does not support any `S`s
